# Generated by Django 5.2.11 on 2026-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(db_index=True, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('server_id', models.UUIDField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
    ]
