# Generated by Django 5.2.11 on 2026-03-10 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=5)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sync_offlin_status_b13188_idx')],
            },
        ),
    ]
