# Generated by Django 5.2.11 on 2026-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_superusers_role_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('SNOOKER_STAFF', 'Snooker Staff')], max_length=15),
        ),
    ]
