# Generated by Django 5.2.11 on 2026-02-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablesession",
            name="guest_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
