# Generated by Django 5.2.11 on 2026-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tablesession_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], db_index=True, default='AVAILABLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['table', 'is_active', 'closed_at'], name='tables_tabl_table_i_005d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['is_active', 'created_at'], name='tables_tabl_is_acti_ea2591_idx'),
        ),
    ]
