# Generated by Django 5.2.11 on 2026-03-18 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_default_ingredient_category(apps, schema_editor):
    IngredientCategory = apps.get_model("inventory", "IngredientCategory")
    IngredientCategory.objects.using(schema_editor.connection.alias).update_or_create(
        id=uuid.UUID("00000000-0000-0000-0000-000000000001"),
        defaults={"name": "OTHERS", "is_active": True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_is_active_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_ingredient_category, migrations.RunPython.noop),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(default=uuid.UUID('00000000-0000-0000-0000-000000000001'), on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='inventory.ingredientcategory'),
        ),
    ]
