"""
Django settings for cafe_billing_backend project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import logging
import os
import psycopg2
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'assets',
    'products',
    'tables',
    'orders',
    'payments',
    'inventory',
    'rest_framework',
    'reports',
    'gaming',
    'rest_framework_simplejwt',
    'sync',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cafe_billing_backend.middleware.DatabaseFailureShieldMiddleware',
    'cafe_billing_backend.middleware.OfflineAwareMiddleware',
]

ROOT_URLCONF = 'cafe_billing_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cafe_billing_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ── Connectivity check ───────────────────────────────────────────────
def _check_neon_connectivity():
    """DB-level connectivity check to avoid socket false positives."""
    if os.getenv("FORCE_OFFLINE_MODE", "").strip().lower() in {"1", "true", "yes"}:
        return False

    host = os.getenv("DB_HOST", "")
    port = int(os.getenv("DB_PORT", "5432"))
    timeout = min(int(os.getenv("DB_CONNECT_TIMEOUT", "5")), 5)
    if not host:
        return False

    try:
        conn = psycopg2.connect(
            dbname=os.getenv("DB_NAME", "neondb"),
            user=os.getenv("DB_USER", "neondb_owner"),
            password=os.getenv("DB_PASSWORD", ""),
            host=host,
            port=port,
            connect_timeout=timeout,
            sslmode=os.getenv("DB_SSLMODE", "require"),
            channel_binding=os.getenv("DB_CHANNEL_BINDING", "require"),
        )
        with conn.cursor() as cursor:
            cursor.execute("SELECT 1")
            cursor.fetchone()
        conn.close()
        return True
    except Exception:
        return False

_IS_ONLINE = _check_neon_connectivity()
OFFLINE_MODE = not _IS_ONLINE

if OFFLINE_MODE:
    logging.getLogger("cafe_billing_backend").warning(
        "Neon PostgreSQL unreachable — starting in OFFLINE mode (SQLite)."
    )

# ── Database definitions ─────────────────────────────────────────────
_NEON_DB = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": os.getenv("DB_NAME", "neondb"),
    "USER": os.getenv("DB_USER", "neondb_owner"),
    "PASSWORD": os.getenv("DB_PASSWORD", ""),
    "HOST": os.getenv(
        "DB_HOST",
        "ep-gentle-haze-aiu8s2kt-pooler.c-4.us-east-1.aws.neon.tech",
    ),
    "PORT": os.getenv("DB_PORT", "5432"),
    "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "300")),
    "CONN_HEALTH_CHECKS": True,
    # Neon pooler uses transaction pooling; server-side cursors are unstable there.
    # Keep this disabled to avoid InvalidCursorName errors during long iterators.
    "DISABLE_SERVER_SIDE_CURSORS": os.getenv(
        "DB_DISABLE_SERVER_SIDE_CURSORS",
        "true",
    ).strip().lower() in {"1", "true", "yes"},
    "OPTIONS": {
        "sslmode": os.getenv("DB_SSLMODE", "require"),
        "channel_binding": os.getenv("DB_CHANNEL_BINDING", "require"),
        "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "8")),
    },
}

_SQLITE_DB = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "db_offline.sqlite3",
}

DATABASES = {
    "default": _SQLITE_DB if OFFLINE_MODE else _NEON_DB,
    "sqlite": _SQLITE_DB,          # always available for local-only models
    "neon": _NEON_DB,               # always available for background sync
}

DATABASE_ROUTERS = ["cafe_billing_backend.db_router.OfflineRouter"]



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.OfflineAwareJWTAuthentication",
    ),
    "EXCEPTION_HANDLER": "cafe_billing_backend.exception_handlers.drf_exception_handler",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ==========================
# MEDIA FILES (Images)
# ==========================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FAST2SMS_API_KEY = os.getenv('FAST2SMS_API_KEY', '')
FAST2SMS_WHATSAPP_TEMPLATE_ID = os.getenv('FAST2SMS_WHATSAPP_TEMPLATE_ID', '')

