# Generated by Django 5.2.11 on 2026-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_base_price_orderitem_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
