# Generated by Django 5.2.11 on 2026-03-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_couponusage_and_coupon_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coupon',
            new_name='orders_coup_is_acti_db61a9_idx',
            old_name='orders_coupo_is_acti_e038b6_idx',
        ),
    ]
