# Generated by Django 5.2.11 on 2026-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
