# Generated by Django 5.2.11 on 2026-02-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_combo_gst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['is_active', 'created_at'], name='products_co_is_acti_8c1353_idx'),
        ),
    ]
